### ISSUE TITLE
problem with proot

### ISSUE THREAD

**Issue by volcanofly** [ledigchr/MALPEM#2] opened 2017-05-19 04:22 UTC
Dear Author,
 After installing it using the installer, I tried to run:
bin/malpem-proot -h

It returns:

> WARNING: Didn't find libGL library in /usr/lib/nvid*, offscreen rendering won't work (only relevant for pdf report)
> 
> Command in CARE environment:
> malpem -h
> proot info: pid 11075: terminated with signal 11

I checked the code in malpem. I think it should print some help info. But it didn't.
Also, when I tried to run:

> bin/malpem-proot -i atlas/pincram/limages/full/m100.nii.gz -o outputDir -t 8

It also returns:

> proot info: pid XXX: terminated with signal 11

I'm not familiar with proot. I was wondering if you could help with this issue.
Thank you!

Best,
Can

**Comment by ledigchr** [comment] 2017-06-21 22:05
Hi Can, I think this is related to a proot issue which was raised in:
https://github.com/proot-me/PRoot/issues/106

I can't reproduce the problem at the moment, but perhaps adding
`export PROOT_NO_SECCOMP=1`
to `malpem-proot` solves the problem. It would be great if you could comment on whether this worked in case you try it.

Cheers,
Christian

**Comment by volcanofly** [comment] 2017-12-14 20:56
Thank you so much! It works!
Sorry for late response. I didn't take a loot at this issue until today. I did it in the same way as you suggested and it worked!
Thank you again!

**Comment by Georgejnr01** [comment] 2019-07-31 07:04
I have the same issue...please how did you do it

**Comment by olivierbarret** [comment] 2020-11-05 12:15
Hi all,

Here is what I had to do to make MALPEM work under WSL:

1)      You have to run WSL2, ie use ext4.vhdx. It does not work with WSL1 and rootfs.
2)      I had to remove the –k string option for the kernel from malpem-root. Was giving a sigsecv otherwise.
3)      Had to setup PROOT_NO_SECCOMP=1 otherwise sigsegv
4)      Or replace proot with proot_5.1.1_x86_64_rc2--no-seccomp. proot_5.1.1_x86_64_rc2 was giving sigsegv if PROOT_NO_SECCOMP not defined.

Hope this helps.

Thanks
Olivier

**Comment by ledigchr** [comment] 2021-05-31 22:34
Added `export PROOT_NO_SECCOMP=1` to `malpem-proot` in [malpem-v1.3](https://github.com/ledigchr/MALPEM/releases/tag/v1.3).

This should address the problem at least for non-WSL environments. If using WSL see this issue https://github.com/ledigchr/MALPEM/issues/6

Closing this issue.

**Closed as completed** 2021-05-31 22:37 UTC
